export const organisations = [
  {
    name: "Cloud",
    location: "Høyskolen Kristiania",
    boxHeader: "Vi er Cloud, linjeforeningen for alle IT-studenter ved Høyskolen Kristiania campus Bergen.",
    boxp1: "Cloud har siden IT-linjene startet opp ved Campus Bergen i 2020 jobbet for å gjøre studiehverdagen til medstudentene våre bedre, i tillegg til å fungere som et bindeledd mellom studentene og næringslivet.",
    boxp2: "Vårt ønske er å la våre medstudenter se hvor mange muligheter som finnes innen IT-verden da vår erfaring er at mange studenter ikke vet hvor mange bedrifter som driver med IT eller har egen IT-avdeling. Dette gjør vi gjennom å arrangere både sosiale arrangement og bedriftspresentasjoner med næringslivet i Bergen og omegn.",
    website: "https://linktr.ee/cloud_linjeforening",
    facebook: "https://www.facebook.com/LinjeforeningenCloud",
    instagram: "https://www.instagram.com/linjeforeningencloud/",
    linkedin: "https://www.linkedin.com/company/cloud-linjeforeningen-for-it/",
    participants: "Alle som studerer IT-bachelor på Kristiania campus Bergen. Campus Bergen tilbyr per nå to IT-bachelorgrader: Cybersikkerhet og Informasjonsteknologi: Frontend- og mobilutvikling.",
    epost: "leder.cloud@studentunionen.no",
    address: "Høyskolen Kristiania Campus Bergen på Kalfarlien (gamle Hansa-bryggeriet, Kalfarveien 78C, 5022 Bergen)",
  },
  {
    name: "CybVest",
    location: "Høyskolen Kristiania",
    boxHeader: "Vi er en linjeforening hovedsakelig for Cyber Studenter, men også alle IT studenter her på Høyskolen Kristiania.",
    boxp1: "Vi jobber for å skape spennende sosiale- og faglige arrangementer for studentene. Alle våre arrangementer er gratis å delta på, så mest mulig folk kan være med! Vi planlegger blant annet bedriftspresentasjoner og spillkvelder hvert semester.",
    website: "https://www.studentunionen.no/",
    instagram: "https://www.instagram.com/cybvest/",
    participants: "Hovedsakelig så er det IT / Cyber studenter på HK, men vi er absolutt åpen for at andre IT studenter kan komme på arrangementene våre hvis de vil!",
    epost: "leder.cybvest@studentunionen.no",
    address: "Høyskolen Kristiania Bergen ved Kalfarveien 87C",

  },
  {
    name: "echo",
    location: "Universitetet i Bergen",
    boxHeader: "Linjeforeningen er et sosialt og faglig bindeledd mellom studentene og ledelsen ved Institutt for informatikk, UiB",
    boxp1: "Linjeforeningen jobber for å bedre det sosiale miljøet til studentene, samt ta opp faglige saker. Foreningen er også ett bindeledd mellom studentene og andre studentpolitiske organisasjoner ved Universitetet i Bergen. I tillegg til å kommunisere med instituttet, gjør echo mange små og store tiltak for studentene. Dette inkluderer alt fra å starte opp studentpub til å ha filmklubb, eller å dele ut pris til studentene som er flinkest til å holde lesesalen ryddig.",
    website: "https://echo.uib.no/",
    facebook: "https://www.facebook.com/groups/informatikk/",
    instagram: "https://www.instagram.com/echo_uib/",
    participants: "Informatikkstudenter er automatisk medlem av echo",
    address: "Institutt for informatikk, Thormøhlensgate 55, 5008 Bergen",
    epost: "echo@uib.no",
  },
  {
    name: "Enigma Fintech",
    location: "Universitetet i Bergen",
    boxHeader: "Vi er en interessegruppe for studenter ved sivilingeniørstudiet ITØK",
    boxp1: "Vi bruker det vi lærer for å få sparepengene til ENIGMA til å vokse. Er du interessert i finans og teknologi? Da er Fintech Enigma noe for deg!",
    boxp2: "Dette kan du gjøre som medlem i Fintech Enigma:",
    list: [
      "Utvikle tradingalgoritmer",
      "Forvalte Fintech Enigma-fondet",
      "Utvikle og vedlikeholde nettsiden vår",
      "Komme i kontakt med spennende bedrifter på bedriftspresentasjoner og workshops",
    ],
    website: "www.fintechenigma.no",
    instagram: "https://www.instagram.com/fintechenigma.uib/",
    linkedin: "https://www.linkedin.com/company/fintech-enigma/",
    github: "https://github.com/fintech-enigma",
    participants: "Alle på ITØK kan være med. Vi ser på mulighetene for å åpne for alle, men trenger godkjenningen fra Enigma, som vi tross alt forvalter pengene til. E-post",
    address: "Fosswinckels Gate 14",
    epost: "fintechenigma@gmail.com",
  },
  {
    name: "Enter",
    location: "Universitetet i Bergen",
    boxHeader: "Vi i Enter er studentforeningen ved infomedia-instituttet på Universitetet i Bergen.",
    boxp1: "Det vil si en felles organisasjon for hele instituttet vårt og ikke bare en enkelt linje. Arrangementene vi holder er både sosiale og faglige. De sosiale arrangementene kan være alt fra quiz på diskuterbar eller grilling i parken til gokart eller egne fester på utesteder. De faglige arrangementene kan være bedriftspresentasjoner med ulike bedrifter eller workshops. Innad i Enter har vi en egen bedriftskomite, sosialkomité og PR. Her er det egne oppdrag for hver av komiteene, men vi samarbeider også mye på tvers av hverandre.",
    website: "https://www.svstudent.no/enter",
    instagram: "https://www.instagram.com/enter_uib/",
    linkedin: "https://www.linkedin.com/company/studentforeningen-enter/posts/?feedView=all",
    participants: "Infomedia-studenter er automatisk medlem av Enter",
    address: "SV-fakultetet, Fosswinckels gate 6, Bergen, Norway",
    epost: "Enter@uib.no",
  },
  {
    name: "Helt Sikker",
    location: "Universitetet i Bergen",
    boxHeader: "Er du en student med interesse for datasikkerhet? Er du keen på å lære mer om sikkerhet, og få solid erfaring med styreverv og drifting av en studentorganisasjon?",
    boxp1: "Helt Sikker er en studentorganisasjon ved Universitetet i Bergen. Vår målsetning er å tilby studenter en arena hvor man kan lære mer om informasjonssikkerhet, samtidig som vi bidrar til å bygge et miljø for sikkerhetsinteresserte studenter i Bergen.",
    boxp2: "Helt Sikker ble originalt stiftet av studenter som tilhørte det første kullet av UiBs bachelorprogram i datasikkerhet. Et av våre mål er å komplementere UiBs mer teoretiske tilnærming til sikkerhet ved å arrangere workshops, foredrag, CTF-er, konkurranser og mer.",
    website: "https://heltsikker.no/",
    facebook: "https://www.facebook.com/groups/heltsikker/",
    instagram: "https://www.instagram.com/heltsikker_bergen/",
    linkedin: "https://www.linkedin.com/company/helt-sikker/?viewAsMember=true",
    participants: "Studenter ved UiB interessert i datasikkerhet",
    epost: "styret@heltsikker.no",
    address: "Ingen adresse",
  },
  {
    name: "Inkogvito",
    location: "Universitetet i Bergen",
    boxHeader: "Inkogvito sitt hovedfokus er å styrke det sosiale samholdet og det faglige innholdet knyttet til studiet vårt.",
    boxp1: "Kognitiv Vitenskap er et lite studie hvor hvert kull kun består av 20-30 studenter hvert år. Når klassene er såpass små er det sosiale samholdet og kulturen til studentene desto mer viktig. Derfor ble Inkogvito stiftet i våren 2021 med mål om å bedre studiehverdagen til alle våre studenter. Med dette nye sentraliserte organet for Kognitiv Vitenskap ble det også mulig å ha et mer overordnet fokus på næringsliv og den faglige strukturen til studiet vårt.",
    facebook: "https://www.facebook.com/groups/inkogvito",
    instagram: "https://www.instagram.com/inkogvito.uib/",
    participants: "Alle som studerer Kognitiv Vitenskap har allerede åpen invitasjon til å engasjere seg. Du trenger ikke registrere deg for å bli med.",
    epost: "inkogvito@uib.no",
  },
  {
    name: "ReMIX",
    location: "Universitetet i Bergen",
    boxHeader: "ReMIX er linjeforeningen for medie- og interaksjonsdesign ved UiB.",
    boxp1: "Vi jobber for å skape et inkluderende miljø som styrker både det sosiale og faglige. Gjennom arrangementer, workshops og samarbeid med bransjen kobler vi studiet til arbeidslivet, samtidig som vi bygger et sterkt studentfellesskap.",
    instagram: "https://www.instagram.com/remix_uib/",
    facebook: "https://www.facebook.com/groups/535661775706870/",
    participants: "Alle studenter ved medie- og interaksjonsdesign ved UiB kan være med i linjeforeningen. (master og bachelor)",
    epost: "remix@uibstudent.no",
    address: "Media City Bergen",
  },
];

export const companyLogos = [
  "sparebanken-vest.png",
  "amitec.png",
  "aritma.png",
  "avo.png",
  "skatteetaten.png",
  "sopra_steria.png",
  "bergen_næringsråd.png",
  "bkk.png",
  "bouvet.png",
  "capgemini.png",
  "statens_vegvesen.png",
  "tietoevry.png",
  "cgi.png",
  "computas.png",
  "deloitte.png",
  "digdir.png",
  "twoday.png",
  "vestland_fylkeskommune.png",
  "dnb.png",
  "dnv.png",
  "equinor.png",
  "ey.png",
  "sparebank_1.png",
  "itera.png",
  "kantega.png",
  "knowit.png",
  "machina.png",
  "tryg.png",
  "miles.png",
  "netcompany.png",
  "nordea.png",
  "norgesgruppen.png",
  "vitec.png",
  "norkart.png",
  "pwc.png",
  "sikt.png",
  "simula.png",
  "stacc.png",
  "tv2.png",
  "accenture.png",
  "intility.png",
  "bekk.png",
];
